### ISSUE TITLE
Function coloring on Mac/Linux

### ISSUE THREAD

**Issue by jrdnbradford** [dracula/rstudio#10]
From the UI screenshots it looks like functions are supposed to be `#50fa7b`. On Mac and Linux this coloring is incorrect. Screenshot below.

![image](https://user-images.githubusercontent.com/36420801/158243102-4295bce2-5dcd-4fc4-a065-f661e4c186cd.png)

**Comment by MarcioFCMartins** [comment]
I'm not sure why you have no color, but on my end the coloring is fine:
![image](https://user-images.githubusercontent.com/34938828/158460293-0230c6b8-ec6b-4b3a-bb8b-e3e2092d1703.png)

I'm running pop_os 21.10, Rstudio 2021.09.0

Edit: See https://community.rstudio.com/t/highlight-function-rstudio-theme/27641 to fix it, it's an option in Rstudio :)

**Comment by jrdnbradford** [comment]
Baha, classic. Didn't even think that was potentially the problem. I wonder why that option isn't highlighted by default. Thanks @MarcioFCMartins, I'll close. 👍🏼
